### ISSUE TITLE
Changing the tool class and updating the langchain tools

### ISSUE THREAD

**Issue by thearyanag** [sendaifun/solana-agent-kit#53] opened 2024-12-25 00:05 UTC
**Is your feature request related to a problem? Please describe.**
The current tools under langchain are limited to langchain, and to implement in other frameworks, work needs to be done

**Describe the solution you'd like**
To fix this, we implement an action interface

```
interface Action {
  name: string;
  similes: string[];
  description: string;
  examples: ActionExample[][];
  handler: Handler;
  validate: Validator;
}
```

inspired from eliza, which will make it easier for future development

This can now be plugged into langchain / vercel, given the structure for it

**Additional context**
https://elizaos.github.io/eliza/docs/core/actions/

**Comment by arihantbansal** [comment] 2024-12-25 17:41
Working on this.

**Comment by FahriBilici** [comment] 2024-12-26 21:09
@thearyanag can you review my pr?

**Comment by michaelessiet** [comment] 2024-12-27 16:30
#72 looks light weight and more modular. I think that might be the solution you're looking for @thearyanag

**Comment by thearyanag** [comment] 2024-12-27 19:09
> #72 looks light weight and more modular. I think that might be the solution you're looking for @thearyanag

yes, just waiting for a couple of changes

**Comment by AIFlowML** [comment] 2024-12-27 23:26
Was this already solved ?

**Comment by TEMHITHORPHE** [comment] 2024-12-30 04:51
#101 seems like a duplicate of #72, no?

**Closed** 2024-12-31 21:55 UTC
Labels: enhancement, bounty
